include(CheckCXXCompilerFlag)

check_cxx_compiler_flag(-ftime-trace TimeTraceTests)

add_library(test_common INTERFACE)
target_include_directories(test_common INTERFACE test_common)

if (TimeTraceTests)
  message(STATUS "Compiler supports -ftime-trace")
  option(ENABLE_TIME_TRACE "Enable time tracing for tests" ON)
  if (ENABLE_TIME_TRACE)
    message(STATUS "enabling time tracing for tests")
  else()
    message(STATUS "disabling time tracing for tests")
    SET(TimeTraceTests OFF)
  endif()
else()
  message(STATUS "Compiler does not support -ftime-trace, disabling time tracing for tests")
endif()


function(register_test test_name source)
  set(test_lib_name ${test_name}_lib)
  add_library(${test_lib_name} ${source})
  target_link_libraries(${test_lib_name} PRIVATE templeano test_common)
  set_target_properties(${test_lib_name} PROPERTIES EXCLUDE_FROM_ALL TRUE)
  if (TimeTraceTests)
    set(test_trace_name ${CMAKE_CURRENT_BINARY_DIR}/${test_name}_trace.json)
    target_compile_options(${test_lib_name} PRIVATE -ftime-trace=${test_trace_name})
    set_target_properties(${test_lib_name} PROPERTIES EXTRA_CLEAN_FILES ${test_trace_name})
  endif()
  add_test(NAME ${test_name} COMMAND ${CMAKE_COMMAND} --build ${CMAKE_BINARY_DIR} --target ${test_lib_name})
  if (ARGN)
    list(GET ARGN 0 possible_xfail)
    if (possible_xfail STREQUAL "XFAIL")
      set_property(TEST ${test_name} PROPERTY WILL_FAIL TRUE)
    else()
      message(FATAL_ERROR "Invalid extra argument to register_test ${possible_xfail}")
    endif()
  endif()
endfunction()

register_test(PeanoBasicOps test_peano_basic_arith_ops.cpp)
register_test(PeanoPrimeFacto test_peano_prime_fact.cpp)
register_test(PositionalEncoding test_positional_encoding.cpp)
register_test(ValueHelper test_value_helper.cpp)

# Negative tests
register_test(InvalidEncoderAlphabet negative_tests/test_invalid_duplicate_char_encoder_alphabet.cpp XFAIL)
register_test(InvalidNegSub negative_tests/test_invalid_neg_sub.cpp XFAIL)
register_test(InvalidSymDecode negative_tests/test_invalid_sym_decode.cpp XFAIL)
